apiVersion: v1
kind: Service
metadata:
  # Name of our service
  name: app-nation-api-service
spec:
  # LoadBalancer type to allow external access to multiple ports
  type: LoadBalancer
  selector:
    # Will deliver external traffic to the pod holding each of our containers
    app: app-nation-api
  ports:
    - name: sentiment
      protocol: TCP
      port: 80
      targetPort: 3000