apiVersion: v1
kind: Pod
metadata:
  name: app-nation-api-deployment
  labels:
    app: app-nation-api
spec:
  containers:
    - image: erenalidal/appnation-api:1.0
      name: app-nation-api
      imagePullPolicy: "Always"
      ports:
        - containerPort: 3000
      env:
        - name: NODE_ENV
          value: "production"