version: '3'
services:
  api:
    build:
      context: ./AppNationAPI
      dockerfile: ./Dockerfile
    ports:
      - "8081:3000"
    environment:
      - NODE_ENV=production
  ui:
    build:
      context: ./AppNationUI
      dockerfile: ./Dockerfile
    depends_on:
      - api
    ports:
      - "8080:8080"
    environment:
      - VITE_API_BASE_URL=http://localhost:8081/v1/