apiVersion: v1
kind: Pod
metadata:
  name: app-nation-ui-deployment
  labels:
    app: app-nation-ui
spec:
  containers:
    - image: erenalidal/appnation-ui:1.0
      name: app-nation-ui
      imagePullPolicy: "Always"
      ports:
        - containerPort: 8080